from __future__ import annotations

from copy import deepcopy
from typing import Any

ORGANIZATION_TYPE_OPTIONS: list[str] = [
    "military_unit",
    "police_department",
    "fire_department",
    "emergency_services",
    "government_agency",
    "elected_office",
    "legislative_body",
    "political_campaign",
    "court_or_judicial_office",
    "masonic_lodge",
    "fraternal_order",
    "church_or_ministry",
    "nonprofit",
    "corporation",
    "small_business",
    "school_or_university",
    "hospital_or_healthcare_system",
    "union_or_labor_organization",
    "tribal_government",
    "civic_association",
    "sports_team_or_league",
    "foundation",
    "custom",
]

_DEFAULT_CUSTOMIZATION: dict[str, Any] = {
    "template_is_helper_only": True,
    "allow_custom_profile_fields": True,
    "allow_custom_nodes": True,
    "allow_custom_role_seats": True,
    "allow_custom_transition_event_types": True,
    "allow_custom_support_record_types": True,
    "allow_custom_statuses": True,
    "allow_custom_hierarchy_labels": True,
    "allow_custom_role_titles": True,
    "allow_custom_departments": True,
    "allow_custom_offices": True,
    "allow_custom_jurisdictions": True,
    "allow_custom_positions": True,
}

COMMAND_STRUCTURE_ORGANIZATION_TYPE_OPTIONS: list[str] = [
    "military unit",
    "police department",
    "fire department",
    "elected office",
    "legislative body",
    "government agency",
    "court / judicial office",
    "Masonic lodge",
    "fraternal order",
    "corporation",
    "nonprofit",
    "church / ministry",
    "school / university",
    "hospital / healthcare",
    "union",
    "tribal government",
    "custom",
]

COMMAND_STRUCTURE_ORGANIZATION_SUBTYPE_OPTIONS: dict[str, list[str]] = {
    "military unit": [
        "brigade",
        "battalion",
        "company",
        "platoon",
        "command",
        "wing",
        "squadron",
        "regiment",
        "division",
    ],
    "elected office": [
        "senate office",
        "house office",
        "governor office",
        "mayor office",
        "city council office",
        "county office",
        "campaign office",
        "committee office",
    ],
    "legislative body": [
        "senate office",
        "house office",
        "governor office",
        "mayor office",
        "city council office",
        "county office",
        "campaign office",
        "committee office",
    ],
    "police department": [
        "department",
        "precinct",
        "district",
        "bureau",
        "division",
        "unit",
        "squad",
    ],
    "fire department": [
        "department",
        "station",
        "battalion",
        "engine company",
        "ladder company",
        "rescue company",
        "EMS unit",
    ],
    "Masonic lodge": [
        "lodge",
        "grand lodge",
        "district",
        "chapter",
        "commandery",
        "consistory",
    ],
    "corporation": [
        "corporation",
        "division",
        "department",
        "board",
        "subsidiary",
        "regional office",
        "executive office",
    ],
}

COMMAND_STRUCTURE_ROLE_SEAT_SUGGESTIONS: dict[str, list[str]] = {
    "military unit": ["Commanding Officer", "Executive Officer", "First Sergeant", "Platoon Leader"],
    "police department": ["Chief of Police", "Deputy Chief", "Captain", "Sergeant", "Detective"],
    "fire department": ["Fire Chief", "Deputy Chief", "Battalion Chief", "Captain", "Lieutenant"],
    "elected office": ["Senator", "Representative", "Governor", "Mayor", "Council Member"],
    "legislative body": ["Speaker", "Majority Leader", "Minority Leader", "Committee Chair", "Member"],
    "government agency": ["Director", "Deputy Director", "Chief of Staff", "Commissioner", "Analyst"],
    "court / judicial office": ["Chief Justice", "Judge", "Magistrate", "Clerk", "Bailiff"],
    "Masonic lodge": ["Worshipful Master", "Senior Warden", "Junior Warden", "Secretary", "Treasurer"],
    "fraternal order": ["President", "Vice President", "Secretary", "Treasurer", "Steward"],
    "corporation": ["Chief Executive Officer", "Chief Operating Officer", "Chief Financial Officer", "Vice President", "Director"],
    "nonprofit": ["Executive Director", "Board Chair", "Treasurer", "Secretary", "Program Director"],
    "church / ministry": ["Pastor", "Associate Pastor", "Deacon", "Elder", "Ministry Director"],
    "school / university": ["President", "Provost", "Dean", "Principal", "Department Chair"],
    "hospital / healthcare": ["Chief Medical Officer", "Hospital Administrator", "Medical Director", "Department Chair", "Nursing Director"],
    "union": ["Union President", "Vice President", "Business Agent", "Steward", "Secretary-Treasurer"],
    "tribal government": ["Chief", "Council Chair", "Council Member", "Tribal Administrator", "Secretary"],
    "custom": [],
}

COMMAND_STRUCTURE_PERSON_STATUS_OPTIONS: list[str] = [
    "active",
    "former",
    "retired",
    "transferred",
    "resigned",
    "deceased",
    "emeritus",
    "honorary",
    "acting",
    "interim",
    "suspended",
    "unknown",
]

COMMAND_STRUCTURE_ASSIGNMENT_STATUS_OPTIONS: list[str] = [
    "current",
    "completed",
    "acting",
    "interim",
    "appointed",
    "elected",
    "promoted",
    "transferred",
    "retired",
    "resigned",
    "removed",
    "deceased",
    "unknown",
]

COMMAND_STRUCTURE_TRANSITION_EVENT_OPTIONS: list[str] = [
    "assumed office",
    "assumed command",
    "installed",
    "elected",
    "appointed",
    "promoted",
    "transferred",
    "retired",
    "resigned",
    "removed",
    "deceased",
    "emeritus designation",
    "term ended",
    "office renamed",
    "unit redesignated",
    "department reorganized",
    "jurisdiction changed",
    "district changed",
    "charter updated",
    "custom",
]

COMMAND_STRUCTURE_SUPPORT_RECORD_TYPE_OPTIONS: list[str] = [
    "appointment order",
    "election certification",
    "oath of office",
    "official roster",
    "minutes",
    "board minutes",
    "lodge minutes",
    "promotion order",
    "transfer order",
    "retirement record",
    "service record",
    "charter document",
    "jurisdiction document",
    "committee assignment",
    "command photo",
    "official portrait",
    "ceremony program",
    "support document",
    "custom",
]

COMMAND_STRUCTURE_PRIVACY_OPTIONS: list[str] = [
    "private",
    "workspace only",
    "organization members",
    "public share",
    "restricted / sensitive",
]

COMMAND_STRUCTURE_FORM_BEHAVIOR: dict[str, Any] = {
    "show_suggested_role_seats_after_organization_type_selection": True,
    "allow_custom_role_seats": True,
    "never_overwrite_previous_person_on_leadership_change": True,
    "leadership_changes_create_new_assignment_or_tenure_records": True,
    "ending_a_term_preserves_historical_record": True,
    "replacement_creates_transition_event_and_new_assignment": True,
    "allow_acting_or_interim_role_states": True,
    "support_evidence_upload_per_transition": True,
    "prevent_duplicate_current_assignment_for_same_role_unless_acting_or_interim": True,
    "current_assignment_duplicate_exception_statuses": ["acting", "interim"],
}

ORGANIZATION_TEMPLATE_CATALOG: dict[str, dict[str, Any]] = {
    "military_unit": {
        "display_label": "Military Unit",
        "suggested_profile_fields": [
            "unit_name",
            "branch",
            "command_level",
            "designation",
            "jurisdiction",
            "base_or_station",
            "mission_scope",
        ],
        "suggested_nodes": [
            "Command",
            "Headquarters",
            "Battalion",
            "Company",
            "Platoon",
            "Squad",
            "Support",
            "Operations",
        ],
        "suggested_role_seats": [
            "Commanding Officer",
            "Executive Officer",
            "Operations Officer",
            "First Sergeant",
            "Platoon Leader",
            "Squad Leader",
            "Staff Officer",
        ],
        "suggested_transition_event_types": [
            "appointed",
            "promoted",
            "transferred",
            "reassigned",
            "retired",
            "resigned",
            "deceased",
            "command_changed",
            "unit_reorganized",
        ],
        "suggested_support_record_types": [
            "appointment_order",
            "promotion_order",
            "transfer_order",
            "unit_roster",
            "service_record",
            "official_photo",
        ],
    },
    "police_department": {
        "display_label": "Police Department",
        "suggested_profile_fields": [
            "department_name",
            "jurisdiction",
            "precinct_or_district",
            "badge_authority",
            "city_county_state",
            "station",
            "division",
            "unit",
        ],
        "suggested_nodes": [
            "Chief’s Office",
            "Patrol Division",
            "Investigations",
            "Special Operations",
            "Training",
            "Internal Affairs",
            "Community Relations",
            "Records",
            "Precinct",
            "District",
            "Watch / Shift",
            "Unit / Squad",
        ],
        "suggested_role_seats": [
            "Chief of Police",
            "Deputy Chief",
            "Assistant Chief",
            "Commander",
            "Captain",
            "Lieutenant",
            "Sergeant",
            "Detective",
            "Officer",
            "Watch Commander",
            "Precinct Commander",
            "Training Officer",
            "Public Information Officer",
            "Records Supervisor",
        ],
        "suggested_transition_event_types": [
            "appointed",
            "promoted",
            "transferred",
            "reassigned",
            "retired",
            "resigned",
            "deceased",
            "suspended",
            "restored",
            "unit_reorganized",
            "command_changed",
        ],
        "suggested_support_record_types": [
            "appointment_order",
            "promotion_order",
            "transfer_order",
            "commendation",
            "service_record",
            "retirement_record",
            "unit_roster",
            "badge_assignment_record",
            "ceremony_program",
            "official_photo",
        ],
    },
    "fire_department": {
        "display_label": "Fire Department",
        "suggested_profile_fields": [
            "department_name",
            "jurisdiction",
            "station",
            "battalion",
            "district",
            "company",
            "apparatus_assignment",
        ],
        "suggested_nodes": [
            "Fire Chief’s Office",
            "Battalion",
            "Station",
            "Engine Company",
            "Ladder Company",
            "Rescue Company",
            "EMS Division",
            "Fire Prevention",
            "Training Division",
            "Operations",
            "Logistics",
        ],
        "suggested_role_seats": [
            "Fire Chief",
            "Deputy Fire Chief",
            "Battalion Chief",
            "Captain",
            "Lieutenant",
            "Engineer / Driver",
            "Firefighter",
            "Paramedic",
            "EMT",
            "Fire Marshal",
            "Training Officer",
            "Safety Officer",
            "Station Commander",
        ],
        "suggested_transition_event_types": [
            "appointed",
            "promoted",
            "assigned",
            "transferred",
            "retired",
            "line_of_duty_death",
            "deceased",
            "station_reassigned",
            "company_reorganized",
            "apparatus_reassigned",
        ],
        "suggested_support_record_types": [
            "appointment_record",
            "promotion_record",
            "station_roster",
            "incident_commendation",
            "service_record",
            "retirement_record",
            "ceremony_program",
            "official_photo",
            "unit_history",
        ],
    },
    "emergency_services": {
        "display_label": "Emergency Services",
        "suggested_profile_fields": [
            "agency_name",
            "jurisdiction",
            "district",
            "dispatch_center",
            "response_zones",
            "medical_authority",
        ],
        "suggested_nodes": [
            "Executive Office",
            "Dispatch",
            "Field Operations",
            "EMS",
            "Rescue",
            "Training",
            "Logistics",
            "Communications",
        ],
        "suggested_role_seats": [
            "Director",
            "Deputy Director",
            "Operations Chief",
            "Medical Director",
            "Shift Commander",
            "Supervisor",
            "Paramedic",
            "EMT",
            "Dispatcher",
        ],
        "suggested_transition_event_types": [
            "appointed",
            "promoted",
            "assigned",
            "transferred",
            "retired",
            "resigned",
            "deceased",
            "unit_reorganized",
        ],
        "suggested_support_record_types": [
            "appointment_order",
            "assignment_order",
            "service_record",
            "unit_roster",
            "official_photo",
            "incident_commendation",
        ],
    },
    "government_agency": {
        "display_label": "Government Agency",
        "suggested_profile_fields": [
            "agency_name",
            "jurisdiction",
            "agency_level",
            "enabling_authority",
            "region",
            "office_location",
            "program_scope",
        ],
        "suggested_nodes": [
            "Executive Office",
            "Division",
            "Bureau",
            "Department",
            "Regional Office",
            "Program Office",
            "Compliance Office",
            "Public Affairs",
            "Records Office",
        ],
        "suggested_role_seats": [
            "Director",
            "Deputy Director",
            "Commissioner",
            "Deputy Commissioner",
            "Administrator",
            "Chief Counsel",
            "Chief of Staff",
            "Program Manager",
            "Regional Director",
            "Board Chair",
            "Board Member",
            "Secretary",
            "Treasurer",
            "Public Information Officer",
        ],
        "suggested_transition_event_types": [
            "appointed",
            "sworn_in",
            "promoted",
            "transferred",
            "retired",
            "resigned",
            "term_ended",
            "office_reorganized",
            "board_assignment_changed",
        ],
        "suggested_support_record_types": [
            "appointment_letter",
            "official_roster",
            "board_assignment_record",
            "public_office_record",
            "office_memo",
            "press_release",
        ],
    },
    "elected_office": {
        "display_label": "Elected Office",
        "suggested_profile_fields": [
            "office_name",
            "chamber",
            "district",
            "jurisdiction",
            "state",
            "county",
            "municipality",
            "party",
            "election_cycle",
            "term_dates",
            "committee_assignments",
            "office_location",
        ],
        "suggested_nodes": [
            "Main Office",
            "District Office",
            "Capitol Office",
            "Campaign Office",
            "Policy Team",
            "Communications Team",
            "Constituent Services",
            "Finance / Compliance",
            "Field Team",
            "Committee Office",
        ],
        "suggested_role_seats": [
            "Senator",
            "Representative",
            "Governor",
            "Mayor",
            "Council Member",
            "Commissioner",
            "Chief of Staff",
            "Deputy Chief of Staff",
            "Legislative Director",
            "Communications Director",
            "Press Secretary",
            "Policy Advisor",
            "District Director",
            "Field Director",
            "Campaign Manager",
            "Treasurer",
            "Compliance Officer",
            "Constituent Services Director",
            "Scheduler",
            "Committee Chair",
            "Committee Member",
        ],
        "suggested_transition_event_types": [
            "elected",
            "appointed",
            "sworn_in",
            "reelected",
            "resigned",
            "retired",
            "term_ended",
            "replaced",
            "redistricted",
            "district_changed",
            "committee_assignment_changed",
            "party_changed",
            "office_reorganized",
            "campaign_closed",
            "staff_transition",
        ],
        "suggested_support_record_types": [
            "oath_of_office",
            "election_certification",
            "appointment_letter",
            "official_roster",
            "committee_assignment_record",
            "campaign_filing",
            "public_office_record",
            "press_release",
            "staff_directory",
            "office_memo",
            "public_biography",
        ],
    },
    "legislative_body": {
        "display_label": "Legislative Body",
        "suggested_profile_fields": [
            "body_name",
            "chamber",
            "jurisdiction",
            "state_or_municipality",
            "session_cycle",
            "districting_model",
        ],
        "suggested_nodes": [
            "Chamber Leadership",
            "Member Offices",
            "Committee Office",
            "Rules Office",
            "Clerk Office",
            "Research Office",
            "Public Affairs",
        ],
        "suggested_role_seats": [
            "Speaker",
            "President",
            "Majority Leader",
            "Minority Leader",
            "Whip",
            "Clerk",
            "Member",
            "Committee Chair",
            "Committee Member",
            "Legislative Counsel",
        ],
        "suggested_transition_event_types": [
            "elected",
            "appointed",
            "sworn_in",
            "committee_assignment_changed",
            "party_changed",
            "term_ended",
            "resigned",
            "retired",
            "body_reorganized",
        ],
        "suggested_support_record_types": [
            "oath_of_office",
            "official_roster",
            "committee_assignment_record",
            "session_record",
            "resolution_record",
            "public_biography",
        ],
    },
    "political_campaign": {
        "display_label": "Political Campaign",
        "suggested_profile_fields": [
            "campaign_name",
            "candidate_name",
            "office_sought",
            "jurisdiction",
            "district",
            "party",
            "election_cycle",
            "campaign_hq_location",
        ],
        "suggested_nodes": [
            "Campaign HQ",
            "Field Team",
            "Communications Team",
            "Policy Team",
            "Finance / Compliance",
            "Digital Team",
            "Volunteer Operations",
        ],
        "suggested_role_seats": [
            "Candidate",
            "Campaign Manager",
            "Field Director",
            "Communications Director",
            "Press Secretary",
            "Policy Advisor",
            "Treasurer",
            "Compliance Officer",
            "Volunteer Coordinator",
        ],
        "suggested_transition_event_types": [
            "campaign_launched",
            "staff_transition",
            "appointed",
            "resigned",
            "elected",
            "campaign_closed",
        ],
        "suggested_support_record_types": [
            "campaign_filing",
            "appointment_letter",
            "staff_directory",
            "press_release",
            "office_memo",
            "public_biography",
        ],
    },
    "court_or_judicial_office": {
        "display_label": "Court or Judicial Office",
        "suggested_profile_fields": [
            "court_name",
            "jurisdiction",
            "court_level",
            "judicial_district",
            "division",
            "courthouse_location",
        ],
        "suggested_nodes": [
            "Court",
            "Clerk’s Office",
            "Chambers",
            "Division",
            "Judicial District",
            "Administrative Office",
        ],
        "suggested_role_seats": [
            "Judge",
            "Chief Judge",
            "Associate Judge",
            "Magistrate",
            "Clerk of Court",
            "Court Administrator",
            "Bailiff",
            "Judicial Assistant",
            "Court Reporter",
            "Prosecutor",
            "Public Defender",
            "Counsel",
        ],
        "suggested_transition_event_types": [
            "appointed",
            "elected",
            "sworn_in",
            "assigned",
            "transferred",
            "retired",
            "resigned",
            "term_ended",
            "court_reorganized",
        ],
        "suggested_support_record_types": [
            "appointment_letter",
            "oath_of_office",
            "official_roster",
            "assignment_record",
            "public_office_record",
            "office_memo",
        ],
    },
    "masonic_lodge": {
        "display_label": "Masonic Lodge",
        "suggested_profile_fields": [
            "lodge_name",
            "lodge_number",
            "jurisdiction",
            "grand_lodge_affiliation",
            "charter_date",
            "meeting_location",
        ],
        "suggested_nodes": [
            "Lodge",
            "Officer Line",
            "Committees",
            "Education",
            "Charity",
            "Records",
        ],
        "suggested_role_seats": [
            "Worshipful Master",
            "Senior Warden",
            "Junior Warden",
            "Treasurer",
            "Secretary",
            "Chaplain",
            "Trustee",
        ],
        "suggested_transition_event_types": [
            "elected",
            "appointed",
            "installed",
            "promoted",
            "resigned",
            "retired",
            "line_reorganized",
        ],
        "suggested_support_record_types": [
            "installation_program",
            "officer_roster",
            "appointment_record",
            "charter_record",
            "meeting_minutes",
            "official_photo",
        ],
    },
    "fraternal_order": {
        "display_label": "Fraternal Order",
        "suggested_profile_fields": [
            "order_name",
            "chapter_or_lodge",
            "jurisdiction",
            "district_or_region",
            "meeting_location",
        ],
        "suggested_nodes": [
            "Main Chapter",
            "Executive Board",
            "Committee",
            "Region",
            "Local Chapter",
        ],
        "suggested_role_seats": [
            "President",
            "Vice President",
            "Secretary",
            "Treasurer",
            "Trustee",
            "Committee Chair",
            "Member",
        ],
        "suggested_transition_event_types": [
            "elected",
            "appointed",
            "installed",
            "resigned",
            "retired",
            "chapter_reorganized",
        ],
        "suggested_support_record_types": [
            "officer_roster",
            "appointment_record",
            "meeting_minutes",
            "committee_record",
            "service_record",
            "official_photo",
        ],
    },
    "church_or_ministry": {
        "display_label": "Church or Ministry",
        "suggested_profile_fields": [
            "church_or_ministry_name",
            "denomination",
            "jurisdiction",
            "campus",
            "district_or_region",
            "location",
        ],
        "suggested_nodes": [
            "Main Church",
            "Board",
            "Ministry",
            "Department",
            "Choir",
            "Outreach",
            "Youth Ministry",
            "Missions",
            "Campus",
        ],
        "suggested_role_seats": [
            "Pastor",
            "Senior Pastor",
            "Bishop",
            "Elder",
            "Deacon",
            "Trustee",
            "Minister",
            "Treasurer",
            "Secretary",
            "Choir Director",
            "Youth Pastor",
            "Ministry Leader",
        ],
        "suggested_transition_event_types": [
            "appointed",
            "ordained",
            "installed",
            "transferred",
            "resigned",
            "retired",
            "deceased",
            "ministry_reorganized",
        ],
        "suggested_support_record_types": [
            "appointment_letter",
            "ordination_record",
            "official_roster",
            "service_record",
            "ministry_directory",
            "official_photo",
        ],
    },
    "nonprofit": {
        "display_label": "Nonprofit",
        "suggested_profile_fields": [
            "organization_name",
            "mission_statement",
            "jurisdiction",
            "service_area",
            "tax_status",
            "headquarters_location",
        ],
        "suggested_nodes": [
            "Board",
            "Executive Office",
            "Programs",
            "Development",
            "Finance / Compliance",
            "Community Outreach",
            "Operations",
        ],
        "suggested_role_seats": [
            "Executive Director",
            "Deputy Director",
            "Board Chair",
            "Board Member",
            "Program Director",
            "Development Director",
            "Treasurer",
            "Secretary",
            "Compliance Officer",
        ],
        "suggested_transition_event_types": [
            "appointed",
            "elected",
            "promoted",
            "resigned",
            "retired",
            "board_assignment_changed",
            "organization_reorganized",
        ],
        "suggested_support_record_types": [
            "appointment_letter",
            "official_roster",
            "board_assignment_record",
            "public_office_record",
            "office_memo",
            "press_release",
        ],
    },
    "corporation": {
        "display_label": "Corporation",
        "suggested_profile_fields": [
            "company_name",
            "industry",
            "jurisdiction",
            "headquarters",
            "region",
            "division",
            "business_unit",
        ],
        "suggested_nodes": [
            "Executive Office",
            "Board",
            "Division",
            "Department",
            "Regional Office",
            "Operations",
            "Finance / Compliance",
            "Communications",
        ],
        "suggested_role_seats": [
            "CEO",
            "President",
            "COO",
            "CFO",
            "General Counsel",
            "Chief of Staff",
            "Vice President",
            "Director",
            "Manager",
            "Board Chair",
            "Board Member",
        ],
        "suggested_transition_event_types": [
            "appointed",
            "promoted",
            "transferred",
            "reassigned",
            "resigned",
            "retired",
            "board_assignment_changed",
            "organization_reorganized",
        ],
        "suggested_support_record_types": [
            "appointment_letter",
            "official_roster",
            "board_assignment_record",
            "service_record",
            "office_memo",
            "press_release",
        ],
    },
    "small_business": {
        "display_label": "Small Business",
        "suggested_profile_fields": [
            "business_name",
            "business_type",
            "jurisdiction",
            "location",
            "owner_structure",
            "service_area",
        ],
        "suggested_nodes": [
            "Owner Office",
            "Operations",
            "Sales",
            "Finance",
            "Customer Service",
            "Field Team",
        ],
        "suggested_role_seats": [
            "Owner",
            "Partner",
            "General Manager",
            "Operations Manager",
            "Finance Manager",
            "Team Lead",
            "Staff",
        ],
        "suggested_transition_event_types": [
            "appointed",
            "promoted",
            "reassigned",
            "resigned",
            "retired",
            "business_reorganized",
        ],
        "suggested_support_record_types": [
            "appointment_record",
            "official_roster",
            "service_record",
            "office_memo",
            "public_profile",
        ],
    },
    "school_or_university": {
        "display_label": "School or University",
        "suggested_profile_fields": [
            "institution_name",
            "school_level",
            "jurisdiction",
            "district_or_system",
            "campus",
            "department",
        ],
        "suggested_nodes": [
            "Board",
            "Office of the President",
            "Office of the Principal",
            "Department",
            "Faculty",
            "Athletics",
            "Student Affairs",
            "Alumni Office",
            "Campus",
            "School / College",
        ],
        "suggested_role_seats": [
            "Board Chair",
            "Trustee",
            "President",
            "Chancellor",
            "Provost",
            "Dean",
            "Principal",
            "Assistant Principal",
            "Department Chair",
            "Professor",
            "Coach",
            "Director",
            "Registrar",
        ],
        "suggested_transition_event_types": [
            "appointed",
            "promoted",
            "assigned",
            "transferred",
            "resigned",
            "retired",
            "department_reorganized",
        ],
        "suggested_support_record_types": [
            "appointment_letter",
            "official_roster",
            "department_record",
            "board_assignment_record",
            "office_memo",
            "public_biography",
        ],
    },
    "hospital_or_healthcare_system": {
        "display_label": "Hospital or Healthcare System",
        "suggested_profile_fields": [
            "system_name",
            "facility_name",
            "jurisdiction",
            "region",
            "service_line",
            "department",
            "clinic_or_unit",
        ],
        "suggested_nodes": [
            "Executive Office",
            "Medical Staff",
            "Department",
            "Unit",
            "Service Line",
            "Clinic",
            "Nursing",
            "Administration",
        ],
        "suggested_role_seats": [
            "CEO",
            "Chief Medical Officer",
            "Chief Nursing Officer",
            "Department Chair",
            "Medical Director",
            "Attending Physician",
            "Nurse Manager",
            "Administrator",
            "Compliance Officer",
        ],
        "suggested_transition_event_types": [
            "appointed",
            "promoted",
            "assigned",
            "transferred",
            "resigned",
            "retired",
            "department_reorganized",
        ],
        "suggested_support_record_types": [
            "appointment_letter",
            "official_roster",
            "assignment_record",
            "service_record",
            "compliance_record",
            "official_photo",
        ],
    },
    "union_or_labor_organization": {
        "display_label": "Union or Labor Organization",
        "suggested_profile_fields": [
            "union_name",
            "local_number",
            "jurisdiction",
            "region",
            "chapter",
            "bargaining_scope",
        ],
        "suggested_nodes": [
            "Local",
            "Executive Board",
            "Committee",
            "Region",
            "Chapter",
            "Bargaining Unit",
        ],
        "suggested_role_seats": [
            "President",
            "Vice President",
            "Secretary",
            "Treasurer",
            "Business Agent",
            "Steward",
            "Organizer",
            "Committee Chair",
            "Delegate",
        ],
        "suggested_transition_event_types": [
            "elected",
            "appointed",
            "assigned",
            "resigned",
            "retired",
            "chapter_reorganized",
            "committee_assignment_changed",
        ],
        "suggested_support_record_types": [
            "election_record",
            "appointment_record",
            "official_roster",
            "committee_record",
            "service_record",
            "office_memo",
        ],
    },
    "tribal_government": {
        "display_label": "Tribal Government",
        "suggested_profile_fields": [
            "nation_or_tribe_name",
            "jurisdiction",
            "district_or_region",
            "governing_body",
            "office_location",
            "cultural_scope",
        ],
        "suggested_nodes": [
            "Tribal Council",
            "Executive Office",
            "Department",
            "Committee",
            "Nation / Band / Tribe Office",
        ],
        "suggested_role_seats": [
            "Chairperson",
            "Vice Chairperson",
            "Council Member",
            "Secretary",
            "Treasurer",
            "Chief",
            "Elder",
            "Department Director",
            "Cultural Officer",
        ],
        "suggested_transition_event_types": [
            "elected",
            "appointed",
            "installed",
            "assigned",
            "resigned",
            "retired",
            "council_reorganized",
        ],
        "suggested_support_record_types": [
            "election_record",
            "appointment_record",
            "official_roster",
            "council_record",
            "cultural_record",
            "office_memo",
        ],
    },
    "civic_association": {
        "display_label": "Civic Association",
        "suggested_profile_fields": [
            "association_name",
            "jurisdiction",
            "district_or_region",
            "meeting_location",
            "community_scope",
        ],
        "suggested_nodes": [
            "Executive Board",
            "Committees",
            "Programs",
            "Membership",
            "Community Outreach",
        ],
        "suggested_role_seats": [
            "President",
            "Vice President",
            "Secretary",
            "Treasurer",
            "Committee Chair",
            "Coordinator",
            "Member",
        ],
        "suggested_transition_event_types": [
            "elected",
            "appointed",
            "assigned",
            "resigned",
            "retired",
            "association_reorganized",
        ],
        "suggested_support_record_types": [
            "officer_roster",
            "appointment_record",
            "meeting_minutes",
            "committee_record",
            "press_release",
            "official_photo",
        ],
    },
    "sports_team_or_league": {
        "display_label": "Sports Team or League",
        "suggested_profile_fields": [
            "team_or_league_name",
            "sport",
            "jurisdiction",
            "division_or_conference",
            "home_venue",
            "season_cycle",
        ],
        "suggested_nodes": [
            "Executive Office",
            "Coaching Staff",
            "Team Operations",
            "Player Development",
            "Communications",
            "Compliance",
        ],
        "suggested_role_seats": [
            "Owner",
            "President",
            "General Manager",
            "Head Coach",
            "Assistant Coach",
            "Team Captain",
            "Director",
            "Coordinator",
        ],
        "suggested_transition_event_types": [
            "appointed",
            "promoted",
            "assigned",
            "transferred",
            "resigned",
            "retired",
            "staff_transition",
            "team_reorganized",
        ],
        "suggested_support_record_types": [
            "appointment_record",
            "official_roster",
            "assignment_record",
            "service_record",
            "press_release",
            "official_photo",
        ],
    },
    "foundation": {
        "display_label": "Foundation",
        "suggested_profile_fields": [
            "foundation_name",
            "mission_statement",
            "jurisdiction",
            "service_area",
            "governance_model",
            "headquarters_location",
        ],
        "suggested_nodes": [
            "Board",
            "Executive Office",
            "Programs",
            "Grants Office",
            "Finance / Compliance",
            "Communications",
        ],
        "suggested_role_seats": [
            "Board Chair",
            "Trustee",
            "President",
            "Executive Director",
            "Program Director",
            "Grants Director",
            "Treasurer",
            "Secretary",
            "Compliance Officer",
        ],
        "suggested_transition_event_types": [
            "appointed",
            "elected",
            "promoted",
            "resigned",
            "retired",
            "board_assignment_changed",
            "organization_reorganized",
        ],
        "suggested_support_record_types": [
            "appointment_letter",
            "official_roster",
            "board_assignment_record",
            "grant_record",
            "office_memo",
            "press_release",
        ],
    },
    "custom": {
        "display_label": "Custom",
        "suggested_profile_fields": [],
        "suggested_nodes": [],
        "suggested_role_seats": [],
        "suggested_transition_event_types": [],
        "suggested_support_record_types": [],
        "custom_template_capabilities": {
            "allow_custom_organization_type_label": True,
            "allow_custom_nodes": True,
            "allow_custom_role_seats": True,
            "allow_custom_transition_events": True,
            "allow_custom_support_record_labels": True,
            "allow_custom_statuses": True,
            "allow_custom_hierarchy_labels": True,
        },
        "enforcement": {
            "enforce_package_node_cap": True,
            "enforce_upload_cap": True,
            "enforce_permission_gates": True,
            "enforce_audit_logging": True,
            "enforce_no_duplicate_records": True,
        },
    },
}


def _normalize(value: Any) -> str:
    return str(value or "").strip().lower()


def list_organization_type_options() -> list[str]:
    return list(ORGANIZATION_TYPE_OPTIONS)


def get_organization_template(organization_type: Any) -> dict[str, Any] | None:
    normalized = _normalize(organization_type)
    if normalized not in ORGANIZATION_TEMPLATE_CATALOG:
        return None
    template = deepcopy(ORGANIZATION_TEMPLATE_CATALOG[normalized])
    template["organization_type"] = normalized
    template["customization"] = {
        **deepcopy(_DEFAULT_CUSTOMIZATION),
        **deepcopy(template.get("customization") or {}),
    }
    return template


def get_organization_template_catalog() -> dict[str, Any]:
    templates = {
        organization_type: get_organization_template(organization_type)
        for organization_type in ORGANIZATION_TYPE_OPTIONS
    }
    return {
        "templates_are_helpers": True,
        "organization_type_options": list_organization_type_options(),
        "templates": {key: value for key, value in templates.items() if value is not None},
    }
