from __future__ import annotations

from copy import deepcopy
from typing import Any


PACKAGE_CODE_ALIASES: dict[str, str] = {
    "legacy-snapshot": "legacy_snapshot",
    "legacy_snapshot": "legacy_snapshot",
    "legacy-portrait-intro": "legacy_portrait_intro",
    "legacy_portrait_intro": "legacy_portrait_intro",
    "digital-legacy-portrait": "digital_legacy_portrait",
    "digital_legacy_portrait": "digital_legacy_portrait",
    "starter-family-tree": "household_foundation",
    "starter_family_tree": "household_foundation",
    "household-foundation": "household_foundation",
    "household_foundation": "household_foundation",
    "heirloom-legacy-tree": "heirloom_legacy_tree",
    "heirloom_legacy_tree": "heirloom_legacy_tree",
    "legacy-plus": "legacy_plus",
    "legacy_plus": "legacy_plus",
    "family-estate-concierge": "family_estate_concierge",
    "family_estate_concierge": "family_estate_concierge",
    "command-structure-network": "command_structure_network",
    "command_structure_network": "command_structure_network",
}

ADDON_CODE_ALIASES: dict[str, str] = {
    "extra-upload-pack": "extra_upload_pack",
    "extra_upload_pack": "extra_upload_pack",
    "extra-storage": "extra_storage",
    "extra_storage": "extra_storage",
    "portrait-polish": "portrait_polish",
    "portrait_polish": "portrait_polish",
    "tribute-narration": "tribute_narration",
    "tribute_narration": "tribute_narration",
    "rush-delivery": "rush_delivery",
    "rush_delivery": "rush_delivery",
    "extra-mapped-person": "extra_mapped_person",
    "extra_mapped_person": "extra_mapped_person",
    "extra-zoom-layer": "extra_zoom_layer",
    "extra_zoom_layer": "extra_zoom_layer",
    "additional-narration-minute": "additional_narration_minute",
    "additional_narration_minute": "additional_narration_minute",
    "on-site-photo-scanning": "on_site_photo_scanning",
    "on_site_photo_scanning": "on_site_photo_scanning",
    "extra-linked-household": "extra_linked_household",
    "extra_linked_household": "extra_linked_household",
    "extra-branch": "extra_branch",
    "extra_branch": "extra_branch",
    "white-glove-archive-support": "white_glove_archive_support",
    "white_glove_archive_support": "white_glove_archive_support",
    "extra-org-node": "extra_org_node",
    "extra_org_node": "extra_org_node",
    "extra-org-level": "extra_org_level",
    "extra_org_level": "extra_org_level",
    "extra-admin-seat": "extra_admin_seat",
    "extra_admin_seat": "extra_admin_seat",
    "command-report-addon": "command_report_addon",
    "command_report_addon": "command_report_addon",
}

PACKAGE_CATALOG: dict[str, dict[str, Any]] = {
    "legacy_snapshot": {
        "package_code": "legacy_snapshot",
        "display_name": "Legacy Snapshot",
        "package_lane": "portrait",
        "base_price_usd": 99,
        "maintenance_monthly_usd": 3,
        "maintenance_annual_usd": 30,
        "maintenance_lifetime_usd": 300,
        "maintenance_starts_on_delivery": True,
        "max_households": 0,
        "max_members": 1,
        "max_org_nodes": 0,
        "max_uploads": 3,
        "max_zoom_layers": 0,
        "max_storage_gb": 0.25,
        "can_build_household": False,
        "can_build_family_tree": False,
        "can_build_org_chart": False,
        "can_link_households": False,
        "can_link_org_units": False,
        "can_upload_portraits": True,
        "can_upload_verification_docs": True,
        "can_use_viewer": True,
        "can_use_narration": False,
        "can_use_lineage_certificate": False,
        "can_open_family_intake": False,
        "can_open_org_intake": False,
        "can_use_link_keys": False,
        "can_manage_link_keys": False,
        "allowed_addons": [
            "extra_upload_pack",
            "extra_storage",
            "portrait_polish",
            "rush_delivery",
            "tribute_narration",
        ],
        "upgrade_targets": [
            "legacy_portrait_intro",
            "digital_legacy_portrait",
            "household_foundation",
            "heirloom_legacy_tree",
            "legacy_plus",
            "family_estate_concierge",
        ],
        "status": "active",
    },
    "legacy_portrait_intro": {
        "package_code": "legacy_portrait_intro",
        "display_name": "Legacy Portrait Intro",
        "package_lane": "portrait",
        "base_price_usd": 199,
        "maintenance_monthly_usd": 4,
        "maintenance_annual_usd": 40,
        "maintenance_lifetime_usd": 400,
        "maintenance_starts_on_delivery": True,
        "max_households": 0,
        "max_members": 1,
        "max_org_nodes": 0,
        "max_uploads": 5,
        "max_zoom_layers": 0,
        "max_storage_gb": 0.5,
        "can_build_household": False,
        "can_build_family_tree": False,
        "can_build_org_chart": False,
        "can_link_households": False,
        "can_link_org_units": False,
        "can_upload_portraits": True,
        "can_upload_verification_docs": True,
        "can_use_viewer": True,
        "can_use_narration": False,
        "can_use_lineage_certificate": False,
        "can_open_family_intake": False,
        "can_open_org_intake": False,
        "can_use_link_keys": False,
        "can_manage_link_keys": False,
        "allowed_addons": [
            "extra_upload_pack",
            "extra_storage",
            "portrait_polish",
            "rush_delivery",
            "tribute_narration",
        ],
        "upgrade_targets": [
            "digital_legacy_portrait",
            "household_foundation",
            "heirloom_legacy_tree",
            "legacy_plus",
            "family_estate_concierge",
        ],
        "status": "active",
    },
    "digital_legacy_portrait": {
        "package_code": "digital_legacy_portrait",
        "display_name": "Digital Legacy Portrait",
        "package_lane": "portrait",
        "base_price_usd": 399,
        "maintenance_monthly_usd": 6,
        "maintenance_annual_usd": 60,
        "maintenance_lifetime_usd": 600,
        "maintenance_starts_on_delivery": True,
        "max_households": 0,
        "max_members": 1,
        "max_org_nodes": 0,
        "max_uploads": 10,
        "max_zoom_layers": 0,
        "max_storage_gb": 1,
        "can_build_household": False,
        "can_build_family_tree": False,
        "can_build_org_chart": False,
        "can_link_households": False,
        "can_link_org_units": False,
        "can_upload_portraits": True,
        "can_upload_verification_docs": True,
        "can_use_viewer": True,
        "can_use_narration": False,
        "can_use_lineage_certificate": False,
        "can_open_family_intake": False,
        "can_open_org_intake": False,
        "can_use_link_keys": True,
        "can_manage_link_keys": True,
        "allowed_addons": [
            "extra_upload_pack",
            "extra_storage",
            "portrait_polish",
            "rush_delivery",
            "tribute_narration",
        ],
        "upgrade_targets": [
            "household_foundation",
            "heirloom_legacy_tree",
            "legacy_plus",
            "family_estate_concierge",
        ],
        "status": "active",
    },
    "household_foundation": {
        "package_code": "household_foundation",
        "display_name": "Household Foundation",
        "package_lane": "household",
        "base_price_usd": 799,
        "maintenance_monthly_usd": 9,
        "maintenance_annual_usd": 95,
        "maintenance_lifetime_usd": 900,
        "maintenance_starts_on_delivery": True,
        "max_households": 1,
        "max_members": 6,
        "max_org_nodes": 0,
        "max_uploads": 20,
        "max_zoom_layers": 2,
        "max_storage_gb": 3,
        "can_build_household": True,
        "can_build_family_tree": True,
        "can_build_org_chart": False,
        "can_link_households": False,
        "can_link_org_units": False,
        "can_upload_portraits": True,
        "can_upload_verification_docs": True,
        "can_use_viewer": True,
        "can_use_narration": False,
        "can_use_lineage_certificate": True,
        "can_open_family_intake": True,
        "can_open_org_intake": False,
        "can_use_link_keys": True,
        "can_manage_link_keys": True,
        "allowed_addons": [
            "extra_mapped_person",
            "extra_zoom_layer",
            "extra_storage",
            "rush_delivery",
            "on_site_photo_scanning",
            "additional_narration_minute",
        ],
        "upgrade_targets": [
            "heirloom_legacy_tree",
            "legacy_plus",
            "family_estate_concierge",
        ],
        "status": "active",
    },
    "heirloom_legacy_tree": {
        "package_code": "heirloom_legacy_tree",
        "display_name": "Heirloom Legacy Tree",
        "package_lane": "household",
        "base_price_usd": 1500,
        "maintenance_monthly_usd": 18,
        "maintenance_annual_usd": 180,
        "maintenance_lifetime_usd": 1500,
        "maintenance_starts_on_delivery": True,
        "max_households": 1,
        "max_members": 15,
        "max_org_nodes": 0,
        "max_uploads": 50,
        "max_zoom_layers": 4,
        "max_storage_gb": 10,
        "can_build_household": True,
        "can_build_family_tree": True,
        "can_build_org_chart": False,
        "can_link_households": False,
        "can_link_org_units": False,
        "can_upload_portraits": True,
        "can_upload_verification_docs": True,
        "can_use_viewer": True,
        "can_use_narration": True,
        "can_use_lineage_certificate": True,
        "can_open_family_intake": True,
        "can_open_org_intake": False,
        "can_use_link_keys": True,
        "can_manage_link_keys": True,
        "allowed_addons": [
            "extra_mapped_person",
            "extra_zoom_layer",
            "extra_storage",
            "rush_delivery",
            "on_site_photo_scanning",
            "additional_narration_minute",
        ],
        "upgrade_targets": [
            "legacy_plus",
            "family_estate_concierge",
        ],
        "status": "active",
    },
    "legacy_plus": {
        "package_code": "legacy_plus",
        "display_name": "Legacy Plus",
        "package_lane": "household",
        "base_price_usd": 3200,
        "maintenance_monthly_usd": 28,
        "maintenance_annual_usd": 280,
        "maintenance_lifetime_usd": 2500,
        "maintenance_starts_on_delivery": True,
        "max_households": 1,
        "max_members": 30,
        "max_org_nodes": 0,
        "max_uploads": 100,
        "max_zoom_layers": 5,
        "max_storage_gb": 25,
        "can_build_household": True,
        "can_build_family_tree": True,
        "can_build_org_chart": False,
        "can_link_households": True,
        "can_link_org_units": False,
        "can_upload_portraits": True,
        "can_upload_verification_docs": True,
        "can_use_viewer": True,
        "can_use_narration": True,
        "can_use_lineage_certificate": True,
        "can_open_family_intake": True,
        "can_open_org_intake": False,
        "can_use_link_keys": True,
        "can_manage_link_keys": True,
        "allowed_addons": [
            "extra_mapped_person",
            "extra_zoom_layer",
            "extra_storage",
            "rush_delivery",
            "on_site_photo_scanning",
            "additional_narration_minute",
            "extra_linked_household",
        ],
        "upgrade_targets": [
            "family_estate_concierge",
        ],
        "status": "active",
    },
    "family_estate_concierge": {
        "package_code": "family_estate_concierge",
        "display_name": "Family Estate Concierge",
        "package_lane": "network",
        "base_price_usd": 6500,
        "maintenance_monthly_usd": 60,
        "maintenance_annual_usd": 600,
        "maintenance_lifetime_usd": 5000,
        "maintenance_starts_on_delivery": True,
        "max_households": 3,
        "max_members": 999,
        "max_org_nodes": 0,
        "max_uploads": 250,
        "max_zoom_layers": 999,
        "max_storage_gb": 50,
        "can_build_household": True,
        "can_build_family_tree": True,
        "can_build_org_chart": False,
        "can_link_households": True,
        "can_link_org_units": False,
        "can_upload_portraits": True,
        "can_upload_verification_docs": True,
        "can_use_viewer": True,
        "can_use_narration": True,
        "can_use_lineage_certificate": True,
        "can_open_family_intake": True,
        "can_open_org_intake": False,
        "can_use_link_keys": True,
        "can_manage_link_keys": True,
        "allowed_addons": [
            "extra_mapped_person",
            "extra_zoom_layer",
            "extra_storage",
            "rush_delivery",
            "on_site_photo_scanning",
            "additional_narration_minute",
            "extra_linked_household",
            "extra_branch",
            "white_glove_archive_support",
        ],
        "upgrade_targets": [],
        "status": "active",
    },
    "command_structure_network": {
        "package_code": "command_structure_network",
        "display_name": "Command Structure Network",
        "package_lane": "organization",
        "base_price_usd": 1999,
        "maintenance_monthly_usd": 20,
        "maintenance_annual_usd": 200,
        "maintenance_lifetime_usd": 1500,
        "maintenance_starts_on_delivery": True,
        "max_households": 0,
        "max_members": 0,
        "max_org_nodes": 15,
        "max_uploads": 25,
        "max_zoom_layers": 2,
        "max_storage_gb": 5,
        "can_build_household": False,
        "can_build_family_tree": False,
        "can_build_org_chart": True,
        "can_link_households": False,
        "can_link_org_units": True,
        "can_upload_portraits": True,
        "can_upload_verification_docs": True,
        "can_use_viewer": True,
        "can_use_narration": False,
        "can_use_lineage_certificate": False,
        "can_open_family_intake": False,
        "can_open_org_intake": True,
        "can_use_link_keys": True,
        "can_manage_link_keys": True,
        "allowed_addons": [
            "extra_org_node",
            "extra_org_level",
            "extra_admin_seat",
            "extra_storage",
            "rush_delivery",
            "command_report_addon",
        ],
        "upgrade_targets": [
            "family_estate_concierge",
        ],
        "status": "active",
    },
}

ADDON_CATALOG: dict[str, dict[str, Any]] = {
    "extra_upload_pack": {
        "addon_code": "extra_upload_pack",
        "display_name": "Extra Upload Pack",
        "price_usd": 49,
        "billing_type": "one_time",
        "allowed_lanes": ["portrait", "household", "network", "organization"],
        "status": "active",
    },
    "extra_storage": {
        "addon_code": "extra_storage",
        "display_name": "Extra Storage",
        "price_usd": 50,
        "billing_type": "recurring_or_one_time",
        "allowed_lanes": ["portrait", "household", "network", "organization"],
        "status": "active",
    },
    "portrait_polish": {
        "addon_code": "portrait_polish",
        "display_name": "Portrait Polish",
        "price_usd": 79,
        "billing_type": "one_time",
        "allowed_lanes": ["portrait"],
        "status": "active",
    },
    "tribute_narration": {
        "addon_code": "tribute_narration",
        "display_name": "Tribute Narration",
        "price_usd": 99,
        "billing_type": "one_time",
        "allowed_lanes": ["portrait"],
        "status": "active",
    },
    "rush_delivery": {
        "addon_code": "rush_delivery",
        "display_name": "Rush Delivery",
        "price_usd": None,
        "billing_type": "one_time_percent",
        "allowed_lanes": ["portrait", "household", "network", "organization"],
        "status": "active",
    },
    "extra_mapped_person": {
        "addon_code": "extra_mapped_person",
        "display_name": "Extra Mapped Person",
        "price_usd": 35,
        "billing_type": "one_time",
        "allowed_lanes": ["household", "network"],
        "status": "active",
    },
    "extra_zoom_layer": {
        "addon_code": "extra_zoom_layer",
        "display_name": "Extra Zoom Layer",
        "price_usd": 175,
        "billing_type": "one_time",
        "allowed_lanes": ["household", "network"],
        "status": "active",
    },
    "additional_narration_minute": {
        "addon_code": "additional_narration_minute",
        "display_name": "Additional Narration Minute",
        "price_usd": 200,
        "billing_type": "one_time",
        "allowed_lanes": ["household", "network"],
        "status": "active",
    },
    "on_site_photo_scanning": {
        "addon_code": "on_site_photo_scanning",
        "display_name": "On-Site Photo Scanning",
        "price_usd": 499,
        "billing_type": "one_time",
        "allowed_lanes": ["household", "network"],
        "status": "active",
    },
    "extra_linked_household": {
        "addon_code": "extra_linked_household",
        "display_name": "Extra Linked Household",
        "price_usd": 1000,
        "billing_type": "one_time",
        "allowed_lanes": ["household", "network"],
        "status": "active",
    },
    "extra_branch": {
        "addon_code": "extra_branch",
        "display_name": "Extra Branch",
        "price_usd": 1000,
        "billing_type": "one_time",
        "allowed_lanes": ["network"],
        "status": "active",
    },
    "white_glove_archive_support": {
        "addon_code": "white_glove_archive_support",
        "display_name": "White-Glove Archive Support",
        "price_usd": 1499,
        "billing_type": "one_time",
        "allowed_lanes": ["network"],
        "status": "active",
    },
    "extra_org_node": {
        "addon_code": "extra_org_node",
        "display_name": "Extra Organization Node",
        "price_usd": 45,
        "billing_type": "one_time",
        "allowed_lanes": ["organization"],
        "status": "active",
    },
    "extra_org_level": {
        "addon_code": "extra_org_level",
        "display_name": "Extra Organization Level",
        "price_usd": 175,
        "billing_type": "one_time",
        "allowed_lanes": ["organization"],
        "status": "active",
    },
    "extra_admin_seat": {
        "addon_code": "extra_admin_seat",
        "display_name": "Extra Admin Seat",
        "price_usd": 99,
        "billing_type": "one_time_or_recurring",
        "allowed_lanes": ["organization"],
        "status": "active",
    },
    "command_report_addon": {
        "addon_code": "command_report_addon",
        "display_name": "Command Report Add-On",
        "price_usd": 149,
        "billing_type": "one_time",
        "allowed_lanes": ["organization"],
        "status": "active",
    },
}


def get_package_catalog() -> dict[str, dict[str, Any]]:
    return deepcopy(PACKAGE_CATALOG)


def get_addon_catalog() -> dict[str, dict[str, Any]]:
    return deepcopy(ADDON_CATALOG)


def _normalize_package_code(package_code: str) -> str:
    return PACKAGE_CODE_ALIASES.get(
        str(package_code or "").strip(),
        str(package_code or "").strip(),
    )


def _normalize_addon_code(addon_code: str) -> str:
    return ADDON_CODE_ALIASES.get(
        str(addon_code or "").strip(),
        str(addon_code or "").strip(),
    )


def get_package(package_code: str) -> dict[str, Any] | None:
    normalized = _normalize_package_code(package_code)
    if not normalized:
        return None
    value = PACKAGE_CATALOG.get(normalized)
    return deepcopy(value) if value else None


def get_addon(addon_code: str) -> dict[str, Any] | None:
    normalized = _normalize_addon_code(addon_code)
    if not normalized:
        return None
    value = ADDON_CATALOG.get(normalized)
    return deepcopy(value) if value else None